import { Course, Student, StaffMember, LetterGrade } from './types';

export const GRADE_POINTS: Record<LetterGrade, number> = {
  'A+': 4.0,
  'A': 4.0,
  'A-': 3.7,
  'B+': 3.3,
  'B': 3.0,
  'B-': 2.7,
  'C+': 2.3,
  'C': 2.0,
  'C-': 1.7,
  'D+': 1.3,
  'D': 1.0,
  'F': 0.0,
  'IP': 0.0,
};

export function scoreToLetterGrade(score: number): LetterGrade {
  if (score >= 90) return 'A';
  if (score >= 85) return 'A-';
  if (score >= 80) return 'B+';
  if (score >= 75) return 'B';
  if (score >= 70) return 'B-';
  if (score >= 65) return 'C+';
  if (score >= 60) return 'C';
  if (score >= 55) return 'C-';
  if (score >= 53) return 'D+';
  if (score >= 50) return 'D';
  return 'F';
}

export const INITIAL_COURSES: Course[] = [
  {
    id: 'COMP101',
    code: 'COMP101',
    nameEn: 'Introduction to Computer Science',
    nameAr: 'مقدمة في علوم الحاسب',
    credits: 3,
    department: 'Computer Science',
    level: 1,
    semester: 1,
    prerequisites: [],
    capacity: 60,
    enrolled: 54,
    instructorId: 'INS-402',
    instructorName: 'Dr. Nadia Mostafa',
    schedule: { day: 'Sunday', time: '08:30 - 10:30', room: 'Hall 302' },
  },
  {
    id: 'COMP102',
    code: 'COMP102',
    nameEn: 'Structured Programming (C++)',
    nameAr: 'البرمجة الهيكلية بلغة سي++',
    credits: 3,
    department: 'Computer Science',
    level: 1,
    semester: 1,
    prerequisites: [],
    capacity: 50,
    enrolled: 48,
    instructorId: 'INS-402',
    instructorName: 'Dr. Nadia Mostafa',
    schedule: { day: 'Monday', time: '10:30 - 12:30', room: 'CS Lab 2' },
  },
  {
    id: 'COMP104',
    code: 'COMP104',
    nameEn: 'Object-Oriented Programming (OOP)',
    nameAr: 'البرمجة كائنية التوجه',
    credits: 3,
    department: 'Computer Science',
    level: 1,
    semester: 2,
    prerequisites: ['COMP102'],
    capacity: 50,
    enrolled: 42,
    instructorId: 'INS-402',
    instructorName: 'Dr. Nadia Mostafa',
    schedule: { day: 'Tuesday', time: '12:30 - 14:30', room: 'CS Lab 1' },
  },
  {
    id: 'COMP201',
    code: 'COMP201',
    nameEn: 'Data Structures and Algorithms',
    nameAr: 'تراكيب البيانات والخوارزميات',
    credits: 3,
    department: 'Computer Science',
    level: 2,
    semester: 1,
    prerequisites: ['COMP104'],
    capacity: 45,
    enrolled: 38,
    instructorId: 'INS-402',
    instructorName: 'Dr. Nadia Mostafa',
    schedule: { day: 'Wednesday', time: '08:30 - 10:30', room: 'Amphitheater 4' },
  },
  {
    id: 'COMP202',
    code: 'COMP202',
    nameEn: 'Computer Architecture & Assembly',
    nameAr: 'معمارية الحاسب ولغة التجميع',
    credits: 3,
    department: 'Computer Science',
    level: 2,
    semester: 1,
    prerequisites: ['COMP101'],
    capacity: 40,
    enrolled: 35,
    instructorId: 'INS-403',
    instructorName: 'Dr. Khaled El-Sayed',
    schedule: { day: 'Thursday', time: '10:30 - 12:30', room: 'Hall 204' },
  },
  {
    id: 'COMP204',
    code: 'COMP204',
    nameEn: 'Database Systems & SQL',
    nameAr: 'نظم قواعد البيانات',
    credits: 3,
    department: 'Computer Science',
    level: 2,
    semester: 1,
    prerequisites: ['COMP104'],
    capacity: 45,
    enrolled: 44,
    instructorId: 'INS-403',
    instructorName: 'Dr. Khaled El-Sayed',
    schedule: { day: 'Sunday', time: '12:30 - 14:30', room: 'CS Lab 3' },
  },
  {
    id: 'COMP301',
    code: 'COMP301',
    nameEn: 'Operating Systems',
    nameAr: 'نظم التشغيل',
    credits: 3,
    department: 'Computer Science',
    level: 3,
    semester: 1,
    prerequisites: ['COMP201'],
    capacity: 35,
    enrolled: 35, // FULL CAPACITY for testing
    instructorId: 'INS-403',
    instructorName: 'Dr. Khaled El-Sayed',
    schedule: { day: 'Monday', time: '14:30 - 16:30', room: 'Hall 105' },
  },
  {
    id: 'MATH101',
    code: 'MATH101',
    nameEn: 'Calculus I & Analytic Geometry',
    nameAr: 'حساب التفاضل والتكامل (1) والهندسة التحليلية',
    credits: 3,
    department: 'Mathematics',
    level: 1,
    semester: 1,
    prerequisites: [],
    capacity: 100,
    enrolled: 82,
    instructorId: 'ADV-301',
    instructorName: 'Dr. Ahmed Ezzat',
    schedule: { day: 'Monday', time: '08:30 - 10:30', room: 'Central Amphitheater' },
  },
  {
    id: 'MATH102',
    code: 'MATH102',
    nameEn: 'Calculus II & Multivariable Analysis',
    nameAr: 'حساب التفاضل والتكامل (2)',
    credits: 3,
    department: 'Mathematics',
    level: 1,
    semester: 2,
    prerequisites: ['MATH101'],
    capacity: 70,
    enrolled: 58,
    instructorId: 'ADV-301',
    instructorName: 'Dr. Ahmed Ezzat',
    schedule: { day: 'Wednesday', time: '10:30 - 12:30', room: 'Hall 301' },
  },
  {
    id: 'MATH201',
    code: 'MATH201',
    nameEn: 'Linear Algebra',
    nameAr: 'الجبر الخطي',
    credits: 3,
    department: 'Mathematics',
    level: 2,
    semester: 1,
    prerequisites: ['MATH101'],
    capacity: 50,
    enrolled: 40,
    instructorId: 'ADV-301',
    instructorName: 'Dr. Ahmed Ezzat',
    schedule: { day: 'Tuesday', time: '08:30 - 10:30', room: 'Hall 202' },
  },
  {
    id: 'STAT101',
    code: 'STAT101',
    nameEn: 'Probability & Statistics I',
    nameAr: 'مقدمة في الإحصاء والاحتمالات',
    credits: 3,
    department: 'Statistics',
    level: 1,
    semester: 1,
    prerequisites: [],
    capacity: 65,
    enrolled: 50,
    instructorId: 'INS-404',
    instructorName: 'Dr. Mona Radwan',
    schedule: { day: 'Thursday', time: '08:30 - 10:30', room: 'Hall 108' },
  },
  {
    id: 'PHYS101',
    code: 'PHYS101',
    nameEn: 'General Physics (Mechanics & Heat)',
    nameAr: 'فيزياء عامة (الميكانيكا والحرارة)',
    credits: 3,
    department: 'General Science',
    level: 1,
    semester: 1,
    prerequisites: [],
    capacity: 90,
    enrolled: 75,
    instructorId: 'INS-405',
    instructorName: 'Dr. Hisham Fathy',
    schedule: { day: 'Sunday', time: '10:30 - 12:30', room: 'Physics Amp 2' },
  },
  {
    id: 'CHEM101',
    code: 'CHEM101',
    nameEn: 'General Chemistry I',
    nameAr: 'كيمياء عامة (1)',
    credits: 3,
    department: 'Chemistry',
    level: 1,
    semester: 1,
    prerequisites: [],
    capacity: 80,
    enrolled: 62,
    instructorId: 'INS-406',
    instructorName: 'Dr. Sameh Abdel-Latif',
    schedule: { day: 'Tuesday', time: '10:30 - 12:30', room: 'Chemistry Lab B' },
  },
  {
    id: 'BIOP101',
    code: 'BIOP101',
    nameEn: 'Introduction to Biophysics',
    nameAr: 'مقدمة في الفيزياء الحيوية',
    credits: 3,
    department: 'Biophysics',
    level: 1,
    semester: 2,
    prerequisites: ['PHYS101'],
    capacity: 40,
    enrolled: 30,
    instructorId: 'INS-407',
    instructorName: 'Dr. Yasmine Al-Bakry',
    schedule: { day: 'Wednesday', time: '12:30 - 14:30', room: 'Biophysics Lab' },
  },
  {
    id: 'ENGL101',
    code: 'ENGL101',
    nameEn: 'English for Academic Science',
    nameAr: 'اللغة الإنجليزية التخصصية للعلوم',
    credits: 2,
    department: 'General Science',
    level: 1,
    semester: 1,
    prerequisites: [],
    capacity: 120,
    enrolled: 110,
    instructorId: 'INS-408',
    instructorName: 'Prof. Amira Farag',
    schedule: { day: 'Thursday', time: '12:30 - 14:30', room: 'Main Lecture Hall' },
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: '2201045',
    pin: '1234',
    nameEn: 'Ziad Mohamed Ibrahim',
    nameAr: 'زياد محمد إبراهيم',
    email: 'ziad.2201045@sci.asu.edu.eg',
    major: 'Computer Science',
    level: 2,
    advisorId: 'ADV-301',
    advisorName: 'Dr. Ahmed Ezzat',
    cgpa: 3.40,
    standing: 'GOOD_STANDING',
    completedCredits: 20,
    maxCreditsAllowed: 19,
    transcript: [
      {
        courseId: 'COMP101',
        courseCode: 'COMP101',
        courseNameEn: 'Introduction to Computer Science',
        courseNameAr: 'مقدمة في علوم الحاسب',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'A',
        numericScore: 92,
        qualityPoints: 4.0,
        passed: true,
      },
      {
        courseId: 'COMP102',
        courseCode: 'COMP102',
        courseNameEn: 'Structured Programming (C++)',
        courseNameAr: 'البرمجة الهيكلية بلغة سي++',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'A-',
        numericScore: 88,
        qualityPoints: 3.7,
        passed: true,
      },
      {
        courseId: 'MATH101',
        courseCode: 'MATH101',
        courseNameEn: 'Calculus I & Analytic Geometry',
        courseNameAr: 'حساب التفاضل والتكامل (1)',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'B+',
        numericScore: 82,
        qualityPoints: 3.3,
        passed: true,
      },
      {
        courseId: 'PHYS101',
        courseCode: 'PHYS101',
        courseNameEn: 'General Physics (Mechanics & Heat)',
        courseNameAr: 'فيزياء عامة (الميكانيكا والحرارة)',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'B',
        numericScore: 78,
        qualityPoints: 3.0,
        passed: true,
      },
      {
        courseId: 'ENGL101',
        courseCode: 'ENGL101',
        courseNameEn: 'English for Academic Science',
        courseNameAr: 'اللغة الإنجليزية التخصصية للعلوم',
        credits: 2,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'A',
        numericScore: 91,
        qualityPoints: 4.0,
        passed: true,
      },
      {
        courseId: 'COMP104',
        courseCode: 'COMP104',
        courseNameEn: 'Object-Oriented Programming (OOP)',
        courseNameAr: 'البرمجة كائنية التوجه',
        credits: 3,
        semesterName: 'Spring 2024/2025',
        letterGrade: 'A',
        numericScore: 94,
        qualityPoints: 4.0,
        passed: true,
      },
      {
        courseId: 'MATH102',
        courseCode: 'MATH102',
        courseNameEn: 'Calculus II & Multivariable Analysis',
        courseNameAr: 'حساب التفاضل والتكامل (2)',
        credits: 3,
        semesterName: 'Spring 2024/2025',
        letterGrade: 'B+',
        numericScore: 81,
        qualityPoints: 3.3,
        passed: true,
      },
    ],
    currentRegistration: [
      { courseId: 'COMP201', status: 'pending_advisor', registeredAt: '2026-09-28' },
      { courseId: 'COMP202', status: 'pending_advisor', registeredAt: '2026-09-28' },
      { courseId: 'COMP204', status: 'pending_advisor', registeredAt: '2026-09-28' },
      { courseId: 'MATH201', status: 'pending_advisor', registeredAt: '2026-09-28' },
      { courseId: 'STAT101', status: 'pending_advisor', registeredAt: '2026-09-28' },
    ],
    registrationStatus: 'pending_advisor',
    advisorNotes: 'Please confirm lab section availability for COMP204.',
  },
  {
    id: '2201890',
    pin: '5678',
    nameEn: 'Omar Yasser El-Gammal',
    nameAr: 'عمر ياسر الجمال',
    email: 'omar.2201890@sci.asu.edu.eg',
    major: 'Computer Science',
    level: 2,
    advisorId: 'ADV-301',
    advisorName: 'Dr. Ahmed Ezzat',
    cgpa: 1.85,
    standing: 'PROBATION',
    completedCredits: 11,
    maxCreditsAllowed: 12, // Strict 12 credit cap due to Academic Probation!
    transcript: [
      {
        courseId: 'COMP101',
        courseCode: 'COMP101',
        courseNameEn: 'Introduction to Computer Science',
        courseNameAr: 'مقدمة في علوم الحاسب',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'C',
        numericScore: 61,
        qualityPoints: 2.0,
        passed: true,
      },
      {
        courseId: 'COMP102',
        courseCode: 'COMP102',
        courseNameEn: 'Structured Programming (C++)',
        courseNameAr: 'البرمجة الهيكلية بلغة سي++',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'D',
        numericScore: 51,
        qualityPoints: 1.0,
        passed: true,
      },
      {
        courseId: 'MATH101',
        courseCode: 'MATH101',
        courseNameEn: 'Calculus I & Analytic Geometry',
        courseNameAr: 'حساب التفاضل والتكامل (1)',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'F',
        numericScore: 42,
        qualityPoints: 0.0,
        passed: false, // FAILED! Blocks MATH102 and MATH201
      },
      {
        courseId: 'PHYS101',
        courseCode: 'PHYS101',
        courseNameEn: 'General Physics (Mechanics & Heat)',
        courseNameAr: 'فيزياء عامة (الميكانيكا والحرارة)',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'C-',
        numericScore: 57,
        qualityPoints: 1.7,
        passed: true,
      },
      {
        courseId: 'ENGL101',
        courseCode: 'ENGL101',
        courseNameEn: 'English for Academic Science',
        courseNameAr: 'اللغة الإنجليزية التخصصية للعلوم',
        credits: 2,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'B',
        numericScore: 76,
        qualityPoints: 3.0,
        passed: true,
      },
    ],
    currentRegistration: [
      { courseId: 'MATH101', status: 'draft', registeredAt: '2026-09-30' }, // Repeating failed course
      { courseId: 'COMP104', status: 'draft', registeredAt: '2026-09-30' },
      { courseId: 'STAT101', status: 'draft', registeredAt: '2026-09-30' },
    ],
    registrationStatus: 'draft',
    advisorNotes: 'URGENT: Student on Academic Probation (CGPA < 2.00). Must repeat MATH101 to lift prerequisites. Max load strictly capped at 12 Credit Hours.',
  },
  {
    id: '2202110',
    pin: '2468',
    nameEn: 'Sara Mahmoud Hassan',
    nameAr: 'سارة محمود حسن',
    email: 'sara.2202110@sci.asu.edu.eg',
    major: 'Biophysics',
    level: 2,
    advisorId: 'ADV-301',
    advisorName: 'Dr. Ahmed Ezzat',
    cgpa: 3.12,
    standing: 'GOOD_STANDING',
    completedCredits: 17,
    maxCreditsAllowed: 19,
    transcript: [
      {
        courseId: 'PHYS101',
        courseCode: 'PHYS101',
        courseNameEn: 'General Physics (Mechanics & Heat)',
        courseNameAr: 'فيزياء عامة (الميكانيكا والحرارة)',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'A-',
        numericScore: 86,
        qualityPoints: 3.7,
        passed: true,
      },
      {
        courseId: 'CHEM101',
        courseCode: 'CHEM101',
        courseNameEn: 'General Chemistry I',
        courseNameAr: 'كيمياء عامة (1)',
        credits: 3,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'B',
        numericScore: 77,
        qualityPoints: 3.0,
        passed: true,
      },
      {
        courseId: 'ENGL101',
        courseCode: 'ENGL101',
        courseNameEn: 'English for Academic Science',
        courseNameAr: 'اللغة الإنجليزية التخصصية للعلوم',
        credits: 2,
        semesterName: 'Fall 2024/2025',
        letterGrade: 'A',
        numericScore: 90,
        qualityPoints: 4.0,
        passed: true,
      },
      {
        courseId: 'BIOP101',
        courseCode: 'BIOP101',
        courseNameEn: 'Introduction to Biophysics',
        courseNameAr: 'مقدمة في الفيزياء الحيوية',
        credits: 3,
        semesterName: 'Spring 2024/2025',
        letterGrade: 'B+',
        numericScore: 83,
        qualityPoints: 3.3,
        passed: true,
      },
      {
        courseId: 'MATH101',
        courseCode: 'MATH101',
        courseNameEn: 'Calculus I & Analytic Geometry',
        courseNameAr: 'حساب التفاضل والتكامل (1)',
        credits: 3,
        semesterName: 'Spring 2024/2025',
        letterGrade: 'C+',
        numericScore: 68,
        qualityPoints: 2.3,
        passed: true,
      },
      {
        courseId: 'COMP101',
        courseCode: 'COMP101',
        courseNameEn: 'Introduction to Computer Science',
        courseNameAr: 'مقدمة في علوم الحاسب',
        credits: 3,
        semesterName: 'Spring 2024/2025',
        letterGrade: 'B',
        numericScore: 78,
        qualityPoints: 3.0,
        passed: true,
      },
    ],
    currentRegistration: [
      { courseId: 'MATH102', status: 'approved', registeredAt: '2026-09-25' },
      { courseId: 'STAT101', status: 'approved', registeredAt: '2026-09-25' },
    ],
    registrationStatus: 'approved',
    advisorNotes: 'Schedule approved for Biophysics sophomore year.',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'ADV-301',
    pin: '1111',
    nameEn: 'Dr. Ahmed Ezzat',
    nameAr: 'د. أحمد عزت',
    role: 'advisor',
    department: 'Mathematics & Computer Science',
    title: 'Associate Professor & Senior Academic Advisor',
    assignedAdviseeIds: ['2201045', '2201890', '2202110'],
  },
  {
    id: 'INS-402',
    pin: '2222',
    nameEn: 'Dr. Nadia Mostafa',
    nameAr: 'د. نادية مصطفى',
    role: 'instructor',
    department: 'Computer Science',
    title: 'Professor of Computer Science',
    assignedCourses: ['COMP101', 'COMP102', 'COMP104', 'COMP201'],
  },
  {
    id: 'ADM-001',
    pin: '9999',
    nameEn: 'Eng. Tarek Mansour',
    nameAr: 'م. طارق منصور',
    role: 'admin',
    department: 'SIS Directorate & Student Affairs',
    title: 'Director of Credit Hour Affairs & IT Operations',
  },
];

export const DEPARTMENTS = [
  'Computer Science',
  'Mathematics',
  'Statistics',
  'Biophysics',
  'Chemistry',
  'General Science',
];

export const MAJORS = [
  'Computer Science',
  'Pure Mathematics & CS (Double Major)',
  'Statistics',
  'Biophysics',
  'Chemistry',
];

// Calculate GPA helper
export function calculateGPA(transcript: { credits: number; qualityPoints: number; passed: boolean }[]): {
  cgpa: number;
  totalCredits: number;
  earnedCredits: number;
} {
  let totalQualityScore = 0;
  let totalAttemptedCredits = 0;
  let earnedCredits = 0;

  for (const entry of transcript) {
    totalAttemptedCredits += entry.credits;
    totalQualityScore += entry.qualityPoints * entry.credits;
    if (entry.passed) {
      earnedCredits += entry.credits;
    }
  }

  const cgpa = totalAttemptedCredits > 0 ? parseFloat((totalQualityScore / totalAttemptedCredits).toFixed(2)) : 0;
  return { cgpa, totalCredits: totalAttemptedCredits, earnedCredits };
}
